### ISSUE TITLE
Invalid documentation

### ISSUE THREAD

**Issue by jjmontgo** [GoogleCloudPlatform/appengine-php-guestbook#17]
The documentation which uses this project is referring to a sign-in link that doesn't exist:

https://cloud.google.com/appengine/docs/php/getting-started/creating-guestbook

**Comment by markoazul** [comment]
here is the right link
https://cloud.google.com/appengine/docs/standard/php/getting-started/creating-guestbook

**Comment by bshaffer** [comment]
I cannot find the broken link in question, and the URL above redirects to the new link. Closing.
